### ISSUE TITLE
Update packagist to 1.1

### ISSUE THREAD

**Issue by 0xBADBAC0N** [24metrics/Fraudshield-php-sdk#3]
Hi,
I saw you tagged the new version on github last week, but it seems like there is no hook activated for packagist and you have to manually trigger it since there it is still version 1.0 :)
https://packagist.org/packages/fraudshield/fraudshield-php

Best regards,
Hendrik

**Comment by djug** [comment]
Ah,
you are right
I have completely forgotten about this

I just added the hook, and performed an update on packagist

THANK YOU!! :)
